apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: hm716/account
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name:
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-url

---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: LoadBalancer
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30105